language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r barter_network/requirements.txt --use-mirrors
script:
  - python barter_network/testing.py --cov-report term-missing --cov app -v