language: python
python:
  - "2.7"
cache: pip
virtualenv:
  system_site_packages: true
before_install:
    - "sudo apt-get build-dep python-scipy"
    - "pip install coveralls"        
    - "pip install scipy"
    - "pip install unittest"
install:
  - "pip install -r barter_network/requirements.txt"

before-script:
  - "python runserver.py"
script: nosetests